version: '3.4'

services:
  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: API/Dockerfile
    ports:
      - "80:80"
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=chefblock;User Id=sa;Password=YourStrongPassword!
  sqlserver:
    image: "mcr.microsoft.com/mssql/server"
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrongPassword!
