// <auto-generated />
using System;
using Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("User")
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.RecipeEntities.CookingStep", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Order")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.ToTable("CookingStep", "Recipe");
                });

            modelBuilder.Entity("Domain.Entities.RecipeEntities.CookingTechnique", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("CookingTechnique", "Recipe");
                });

            modelBuilder.Entity("Domain.Entities.RecipeEntities.Country", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("GeneratedRecipeID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GeneratedRecipeID"));

                    b.Property<int>("FoodInformationId")
                        .HasColumnType("int");

                    b.HasKey("GeneratedRecipeID");

                    b.ToTable("GeneratedRecipe", "Recipe");
                });

            modelBuilder.Entity("Domain.Entities.RecipeEntities.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Ingredient", "Recipe");
                });

            modelBuilder.Entity("Domain.Entities.RecipeEntities.MealTime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MealTimeEnum")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("MealTime", "Recipe");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MealTimeEnum = 1
                        },
                        new
                        {
                            Id = 2,
                            MealTimeEnum = 2
                        },
                        new
                        {
                            Id = 3,
                            MealTimeEnum = 3
                        },
                        new
                        {
                            Id = 4,
                            MealTimeEnum = 4
                        },
                        new
                        {
                            Id = 5,
                            MealTimeEnum = 5
                        });
                });

            modelBuilder.Entity("Domain.Entities.RecipeEntities.MealType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MealName")
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("MealType", "Recipe");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MealName = 1
                        },
                        new
                        {
                            Id = 2,
                            MealName = 2
                        },
                        new
                        {
                            Id = 3,
                            MealName = 3
                        },
                        new
                        {
                            Id = 4,
                            MealName = 4
                        },
                        new
                        {
                            Id = 5,
                            MealName = 5
                        },
                        new
                        {
                            Id = 6,
                            MealName = 6
                        });
                });

            modelBuilder.Entity("Domain.Entities.RecipeEntities.RecipeDietPreference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DietaryPreferences")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("RecipeDietPreference", "Recipe");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DietaryPreferences = 1
                        },
                        new
                        {
                            Id = 2,
                            DietaryPreferences = 2
                        },
                        new
                        {
                            Id = 3,
                            DietaryPreferences = 3
                        },
                        new
                        {
                            Id = 4,
                            DietaryPreferences = 4
                        },
                        new
                        {
                            Id = 5,
                            DietaryPreferences = 5
                        },
                        new
                        {
                            Id = 6,
                            DietaryPreferences = 6
                        },
                        new
                        {
                            Id = 7,
                            DietaryPreferences = 7
                        });
                });

            modelBuilder.Entity("Domain.Entities.RecipeEntities.Region", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("RegionName")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Region", "Recipe");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RegionName = 1
                        },
                        new
                        {
                            Id = 2,
                            RegionName = 2
                        },
                        new
                        {
                            Id = 3,
                            RegionName = 3
                        },
                        new
                        {
                            Id = 4,
                            RegionName = 4
                        },
                        new
                        {
                            Id = 5,
                            RegionName = 5
                        },
                        new
                        {
                            Id = 6,
                            RegionName = 6
                        },
                        new
                        {
                            Id = 7,
                            RegionName = 7
                        });
                });

            modelBuilder.Entity("Domain.Entities.UserEntities.BloodType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BloodTypeName")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("BloodTypes", "User");
                });

            modelBuilder.Entity("Domain.Entities.UserEntities.DietaryPreferences", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("DietaryPreferenceID");

                    b.Property<int>("AllowedDietaryPreferences")
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DietaryPreferences", "User");
                });

            modelBuilder.Entity("Domain.Entities.UserEntities.SocialMediaHandle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SocialMediaId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Handle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int>("UserProfileInfoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileInfoId");

                    b.ToTable("SocialMediaHandles", "User");
                });

            modelBuilder.Entity("Domain.Entities.UserEntities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserId");

                    b.ToTable("User", "User");
                });

            modelBuilder.Entity("Domain.Entities.UserEntities.UserActivityLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("ActivityDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ActivityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("BrowserType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("BrowserVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DeviceOS")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DeviceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("Duration")
                        .HasColumnType("int");

                    b.Property<string>("IPAddress")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserActivityLog", "User");
                });

            modelBuilder.Entity("Domain.Entities.UserEntities.UserAllergy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SeverityLevel")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserAllergy", "User");
                });

            modelBuilder.Entity("Domain.Entities.UserEntities.UserCookingSkillLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SkillLevelId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CookingSkillLevel")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserCookingSkillLevel", "User");
                });

            modelBuilder.Entity("Domain.Entities.UserEntities.UserCredentials", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("AccountCreationDateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("AccountStatus")
                        .HasColumnType("int");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("LastLoginDateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTimeOffset?>("PasswordResetExpirationDateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("PasswordResetToken")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserId");

                    b.ToTable("UserCredentials", "User");
                });

            modelBuilder.Entity("Domain.Entities.UserEntities.UserNotification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("NotificationText")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("NotificationType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserNotification", "User");
                });

            modelBuilder.Entity("Domain.Entities.UserEntities.UserProfileInfo", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("AccountCreationDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<bool>("IsBlacklisted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSuspicious")
                        .HasColumnType("bit");

                    b.Property<string>("LanguagePreference")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTimeOffset>("LastLoginDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("NotificationSettings")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentInformation")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ProfilePicture")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("SocialMediaHandle")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("SubscriptionStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("UserActivityLog")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("UserProfileInfo", "User");
                });

            modelBuilder.Entity("Domain.Entities.RecipeEntities.CookingStep", b =>
                {
                    b.HasOne("Domain.Entities.RecipeEntities.GeneratedRecipe", null)
                        .WithMany("CookingSteps")
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.RecipeEntities.FoodInformation", b =>
                {
                    b.HasOne("Domain.Entities.RecipeEntities.GeneratedRecipe", null)
                        .WithOne("FoodInformation")
                        .HasForeignKey("Domain.Entities.RecipeEntities.FoodInformation", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.RecipeEntities.Ingredient", b =>
                {
                    b.HasOne("Domain.Entities.RecipeEntities.GeneratedRecipe", null)
                        .WithMany("Ingredients")
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.UserEntities.DietaryPreferences", b =>
                {
                    b.HasOne("Domain.Entities.UserEntities.User", null)
                        .WithMany("DietaryPreferences")
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.UserEntities.SocialMediaHandle", b =>
                {
                    b.HasOne("Domain.Entities.UserEntities.UserProfileInfo", null)
                        .WithMany("SocialMediaHandles")
                        .HasForeignKey("UserProfileInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.UserEntities.UserActivityLog", b =>
                {
                    b.HasOne("Domain.Entities.UserEntities.User", null)
                        .WithOne("UserActivityLog")
                        .HasForeignKey("Domain.Entities.UserEntities.UserActivityLog", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.UserEntities.UserAllergy", b =>
                {
                    b.HasOne("Domain.Entities.UserEntities.User", null)
                        .WithMany("UserAllergies")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.UserEntities.UserCookingSkillLevel", b =>
                {
                    b.HasOne("Domain.Entities.UserEntities.User", null)
                        .WithOne("UserCookingSkillLevel")
                        .HasForeignKey("Domain.Entities.UserEntities.UserCookingSkillLevel", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.UserEntities.UserCredentials", b =>
                {
                    b.HasOne("Domain.Entities.UserEntities.User", null)
                        .WithOne("UserCredentials")
                        .HasForeignKey("Domain.Entities.UserEntities.UserCredentials", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.UserEntities.UserNotification", b =>
                {
                    b.HasOne("Domain.Entities.UserEntities.User", null)
                        .WithMany("UserNotifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.UserEntities.UserProfileInfo", b =>
                {
                    b.HasOne("Domain.Entities.UserEntities.User", null)
                        .WithOne("UserProfileInfo")
                        .HasForeignKey("Domain.Entities.UserEntities.UserProfileInfo", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.RecipeEntities.GeneratedRecipe", b =>
                {
                    b.Navigation("CookingSteps");

                    b.Navigation("FoodInformation")
                        .IsRequired();

                    b.Navigation("Ingredients");
                });

            modelBuilder.Entity("Domain.Entities.UserEntities.User", b =>
                {
                    b.Navigation("DietaryPreferences");

                    b.Navigation("UserActivityLog")
                        .IsRequired();

                    b.Navigation("UserAllergies");

                    b.Navigation("UserCookingSkillLevel")
                        .IsRequired();

                    b.Navigation("UserCredentials")
                        .IsRequired();

                    b.Navigation("UserNotifications");

                    b.Navigation("UserProfileInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.UserEntities.UserProfileInfo", b =>
                {
                    b.Navigation("SocialMediaHandles");
                });
#pragma warning restore 612, 618
        }
    }
}
